# Generated by Django 5.2.8 on 2025-11-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date/heure de la lecture.')),
                ('sensor_type', models.CharField(choices=[('moisture', 'Soil moisture'), ('temperature', 'Air temperature'), ('humidity', 'Humidity')], help_text='Type de capteur (moisture, temperature, humidity).', max_length=20)),
                ('value', models.FloatField(help_text='Valeur numérique mesurée.')),
                ('unit', models.CharField(blank=True, default='', help_text='Unité (%, °C, etc.).', max_length=20)),
                ('source', models.CharField(choices=[('simulator', 'Simulator'), ('manual', 'Manual entry'), ('device', 'Physical sensor')], default='simulator', help_text='Origine de la donnée.', max_length=20)),
                ('plot', models.ForeignKey(help_text='Parcelle à laquelle appartient cette mesure.', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.fieldplot')),
            ],
            options={
                'verbose_name': 'Lecture capteur',
                'verbose_name_plural': 'Lectures capteurs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plot', 'timestamp'], name='sensors_sen_plot_id_70314a_idx'), models.Index(fields=['sensor_type', 'timestamp'], name='sensors_sen_sensor__f7753b_idx')],
            },
        ),
    ]
