# Generated by Django 5.2.8 on 2025-11-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date/heure de génération de la recommandation.')),
                ('recommended_action', models.TextField(help_text='Action recommandée pour le fermier.')),
                ('explanation_text', models.TextField(help_text="Explication lisible par un humain (template de l'agent).")),
                ('confidence', models.FloatField(help_text='Confiance de la recommandation (0–1).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', help_text='Statut de la recommandation.', max_length=20)),
            ],
            options={
                'verbose_name': 'Recommandation agent',
                'verbose_name_plural': 'Recommandations agent',
                'ordering': ['-timestamp'],
            },
        ),
    ]
