# Generated by Django 5.2.8 on 2025-11-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrecommendation',
            name='anomaly_event',
            field=models.ForeignKey(help_text="Événement d'anomalie lié à cette recommandation.", on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='anomalies.anomalyevent'),
        ),
    ]
