# Generated by Codex on 2025-11-26
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anomalies", "0001_initial"),
        ("agent", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentrecommendation",
            old_name="recommended_action",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="agentrecommendation",
            old_name="explanation_text",
            new_name="explanation",
        ),
        migrations.AlterField(
            model_name="agentrecommendation",
            name="anomaly_event",
            field=models.OneToOneField(
                help_text="Associated anomaly event that triggered this recommendation.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation",
                to="anomalies.anomalyevent",
            ),
        ),
        migrations.AlterField(
            model_name="agentrecommendation",
            name="confidence",
            field=models.FloatField(help_text="Confidence score (0-1)."),
        ),
        migrations.AlterField(
            model_name="agentrecommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                help_text="Current status of the recommendation.",
                max_length=20,
            ),
        ),
    ]
