# Generated by Django 5.2.8 on 2025-11-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_align_recommendation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrecommendation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Agent Recommendation', 'verbose_name_plural': 'Agent Recommendations'},
        ),
        migrations.AlterField(
            model_name='agentrecommendation',
            name='action',
            field=models.TextField(help_text='Action recommended by the agent.'),
        ),
        migrations.AlterField(
            model_name='agentrecommendation',
            name='explanation',
            field=models.TextField(help_text='Human-readable explanation of the recommendation.'),
        ),
        migrations.AlterField(
            model_name='agentrecommendation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Recommendation creation timestamp.'),
        ),
    ]
