# Generated by Django 5.2.8 on 2025-11-24 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom unique de l'exploitation pour ce propriétaire.", max_length=100)),
                ('location', models.CharField(help_text='Localisation générale de la ferme (ville, région, pays).', max_length=255)),
                ('size_ha', models.FloatField(help_text='Superficie de la ferme en hectares.')),
                ('crop_type', models.CharField(help_text='Culture principale (ex: blé, maïs, olivier, etc.).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text="Le propriétaire (utilisateur) de l'exploitation.", on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ferme',
                'verbose_name_plural': 'Fermes',
                'ordering': ['owner', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la parcelle au sein de la ferme.', max_length=100)),
                ('crop_variety', models.CharField(help_text='Variété cultivée dans cette parcelle.', max_length=100)),
                ('area_m2', models.FloatField(help_text='Surface de la parcelle en m².')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Statut de la parcelle.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(help_text='Ferme à laquelle appartient cette parcelle.', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farms.farmprofile')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['farm', 'name'],
                'unique_together': {('farm', 'name')},
            },
        ),
    ]
