# Generated by Django 5.2.8 on 2025-11-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date/heure de détection.')),
                ('anomaly_type', models.CharField(choices=[('irrigation', 'Irrigation issue'), ('heat_stress', 'Heat stress'), ('humidity_issue', 'Humidity issue'), ('multi_factor', 'Multi-factor anomaly')], help_text="Type d'anomalie détectée.", max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Niveau de sévérité.', max_length=10)),
                ('model_confidence', models.FloatField(help_text='Confiance du modèle entre 0 et 1.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Détails supplémentaires (valeurs, fenêtres temporelles, etc.).')),
                ('plot', models.ForeignKey(help_text="Parcelle concernée par l'anomalie.", on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='farms.fieldplot')),
            ],
            options={
                'verbose_name': "Événement d'anomalie",
                'verbose_name_plural': "Événements d'anomalie",
                'ordering': ['-timestamp'],
            },
        ),
    ]
