# Generated by Django 5.2.8 on 2025-11-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyevent',
            name='sensor_reading',
            field=models.ForeignKey(blank=True, help_text="Lecture capteur qui a déclenché l'anomalie (optionnel).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='sensors.sensorreading'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['plot', 'timestamp'], name='anomalies_a_plot_id_5d5985_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['anomaly_type', 'severity'], name='anomalies_a_anomaly_ede557_idx'),
        ),
    ]
